export const headers = [
  {
    name: 'Prop',
    width: '150px',
    uuid: 1,
  },
  {
    name: 'Type',
    width: '100px',
    uuid: 2,
  },
  {
    name: 'Default',
    width: '200px',
    flex_grow: 1,
    uuid: 3,
  },
  {
    name: 'Options',
    width: '200px',
    flex_grow: 1,
    uuid: 4,
  },
  {
    name: 'Description',
    width: '300px',
    uuid: 5,
  },
];

export const theme_rows = [
  {
    name: 'onClick',
    type: 'function',
    default: '() => {}',
    options: '',
    description: 'onClick function for button',
    uuid: 1,
  },
  {
    name: 'left_icon',
    type: 'fontawesome',
    default: 'null',
    options: 'fontawesome icon',
    description: 'optional left icon for a button',
    uuid: 2,
  },
  {
    name: 'right_icon',
    type: 'fontawesome',
    default: 'null',
    options: 'fontawesome icon',
    description: 'optional right icon for a button',
    uuid: 3,
  },
  {
    name: 'variant',
    type: 'string',
    default: 'primary',
    options: 'primary | secondary | blue ...',
    description: 'color variants for button',
    uuid: 4,
  },
  {
    name: 'button_size',
    type: 'string',
    default: 'medium',
    options: 'small | medium | large',
    description: 'button sizing',
    uuid: 5,
  },
  {
    name: 'type',
    type: 'string',
    default: 'button',
    options: 'button | submit',
    description: 'change the button to submit onClick',
    uuid: 6,
  },
  {
    name: 'caret',
    type: 'string',
    default: 'right',
    options: 'top | right | bottom | left',
    description: 'tooltip caret placement if there is a tooltip',
    uuid: 7,
  },
  {
    name: 'theme',
    type: 'object',
    default: '{}',
    options: 'refer to theme',
    description: 'theme override for button',
    uuid: 8,
  },
  {
    name: 'position',
    type: 'object',
    default: `{ right: 'calc(100% + 10px)' }`,
    options: 'inline-css',
    description: 'tooltip placement',
    uuid: 9,
  },
  {
    name: 'tooltip',
    type: 'string',
    default: 'null',
    options: '',
    description: 'shows a tooltip on hover',
    uuid: 10,
  },
  {
    name: 'margin',
    type: 'string',
    default: '0px',
    options: 'inline-css',
    description: 'adds margin to the button',
    uuid: 11,
  },
  {
    name: 'disabled',
    type: 'boolean',
    default: 'false',
    options: 'true | false',
    description: 'disables the button',
    uuid: 12,
  },
  {
    name: 'children',
    type: 'string',
    default: 'null',
    options: '',
    description: 'button value',
    uuid: 13,
  },
];
