export const headers = [
  {
    name: 'Prop',
    width: '150px',
    uuid: 1,
  },
  {
    name: 'Type',
    width: '100px',
    uuid: 2,
  },
  {
    name: 'Default',
    width: '200px',
    flex_grow: 1,
    uuid: 3,
  },
  {
    name: 'Options',
    width: '200px',
    flex_grow: 1,
    uuid: 4,
  },
  {
    name: 'Description',
    width: '300px',
    uuid: 5,
  },
];

export const theme_rows = [
  {
    name: 'onClick',
    type: 'function',
    default: '() => {}',
    options: '',
    description: 'onClick function',
    uuid: 1,
  },
  {
    name: 'left_icon',
    type: 'fontawesome',
    default: 'null',
    options: '',
    description: 'optional fontawesome left icon',
    uuid: 2,
  },
  {
    name: 'right_icon',
    type: 'fontawesome',
    default: 'null',
    options: '',
    description: 'optional fontawesome right icon',
    uuid: 3,
  },
  {
    name: 'variant',
    type: 'string',
    default: 'primary',
    options: 'primary | secondary | blue ...',
    description: 'color variants',
    uuid: 4,
  },
  {
    name: 'button_size',
    type: 'string',
    default: 'medium',
    options: 'small | medium | large',
    description: 'button size',
    uuid: 5,
  },
  {
    name: 'type',
    type: 'string',
    default: 'button',
    options: 'button | submit',
    description: 'html tag attribute',
    uuid: 6,
  },
  {
    name: 'caret',
    type: 'string',
    default: 'right',
    options: 'top | right | bottom | left',
    description: 'caret placement for a tooltip',
    uuid: 7,
  },
  {
    name: 'theme',
    type: 'object',
    default: '{}',
    options: '',
    description: 'theme override',
    uuid: 8,
  },
  {
    name: 'position',
    type: 'object',
    default: `{ right: 'calc(100% + 10px)' }`,
    options: '',
    description: 'tooltip placement on hover',
    uuid: 9,
  },
  {
    name: 'tooltip',
    type: 'string',
    default: 'null',
    options: '',
    description: 'tooltip message',
    uuid: 10,
  },
  {
    name: 'margin',
    type: 'string | number',
    default: '0px',
    options: '',
    description: 'adds margin',
    uuid: 11,
  },
  {
    name: 'disabled',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'disables the button',
    uuid: 12,
  },
  {
    name: 'children',
    type: 'string',
    default: 'null',
    options: '',
    description: 'button value',
    uuid: 13,
  },
  {
    name: 'outline',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'button background is set to #fff',
    uuid: 13,
  },
];
