export const headers = [
  {
    name: 'Prop',
    width: '150px',
    uuid: 1,
  },
  {
    name: 'Type',
    width: '100px',
    uuid: 2,
  },
  {
    name: 'Default',
    width: '200px',
    flex_grow: 1,
    uuid: 3,
  },
  {
    name: 'Options',
    width: '200px',
    flex_grow: 1,
    uuid: 4,
  },
  {
    name: 'Description',
    width: '300px',
    uuid: 5,
  },
];

export const snackbar_rows = [
  {
    name: 'onChange',
    type: 'function',
    default: '() => {}',
    options: '',
    description: 'onChange function fires after duration or action onClick',
    uuid: 1,
  },
  {
    name: 'show',
    type: 'boolean',
    default: 'false',
    options: 'true | false',
    description: 'will show and hide the snackbar',
    uuid: 2,
  },
  {
    name: 'label',
    type: 'string',
    default: 'null',
    options: '',
    description: 'snackbar label text',
    uuid: 3,
  },
  {
    name: 'theme',
    type: 'object',
    default: '{}',
    options: 'refer to theme',
    description: 'theme override for button',
    uuid: 4,
  },
  {
    name: 'position',
    type: 'object',
    default: '{ right: 0, bottom: 0 }',
    options: '',
    description: 'controls the absolute position of the snackbar',
    uuid: 5,
  },
  {
    name: 'action',
    type: 'string',
    default: 'null',
    options: '',
    description: 'provides a snackbar action for users to click',
    uuid: 6,
  },
  {
    name: 'variant',
    type: 'string',
    default: 'null',
    options: 'primary | secondary | red | green | etc...',
    description: 'sets the snackbar theme and can take a variety of colors',
    uuid: 7,
  },
  {
    name: 'width',
    type: 'number',
    default: '250',
    options: '',
    description: 'snackbar set width',
    uuid: 8,
  },
  {
    name: 'duration',
    type: 'number',
    default: 'null',
    options: 'ex. 3000',
    description: 'will fire the onChange event for auto hide capability',
    uuid: 9,
  },
];
