export const headers = [
  {
    name: 'Prop',
    width: '150px',
    uuid: 1,
  },
  {
    name: 'Type',
    width: '100px',
    uuid: 2,
  },
  {
    name: 'Default',
    width: '200px',
    flex_grow: 1,
    uuid: 3,
  },
  {
    name: 'Options',
    width: '200px',
    flex_grow: 1,
    uuid: 4,
  },
  {
    name: 'Description',
    width: '300px',
    uuid: 5,
  },
];

export const checkbox_rows = [
  {
    name: 'onClick',
    type: 'function',
    default: '() => {}',
    options: '',
    description: 'onClick function fires checkbox',
    uuid: 1,
  },
  {
    name: 'highlight',
    type: 'boolean',
    default: 'true',
    options: 'true | false',
    description: 'highlights checkbox label depending on checked prop',
    uuid: 2,
  },
  {
    name: 'children',
    type: 'string',
    default: 'null',
    options: '',
    description: 'checkbox label',
    uuid: 3,
  },
  {
    name: 'theme',
    type: 'object',
    default: '{}',
    options: 'refer to theme',
    description: 'theme override for checkbox',
    uuid: 5,
  },
  {
    name: 'checked',
    type: 'boolean',
    default: 'false',
    options: 'true | false',
    description: 'controls the checkbox checked',
    uuid: 6,
  },
  {
    name: 'margin',
    type: 'string | number',
    default: '0px',
    options: '',
    description: 'sets margin on checkbox',
    uuid: 7,
  },
  {
    name: 'width',
    type: 'number | string',
    default: '100%',
    options: '',
    description: 'sets width on checkbox',
    uuid: 8,
  },
  {
    name: 'height',
    type: 'number',
    default: '30',
    options: '',
    description: 'sets height on checkbox',
    uuid: 9,
  },
  {
    name: 'disabled',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'disables checkbox',
    uuid: 10,
  },
  {
    name: 'native',
    type: 'boolean',
    default: 'true',
    options: '',
    description: 'toggles native input checkbox or fontawesome checkbox',
    uuid: 11,
  },
];
