export const headers = [
  {
    name: 'Prop',
    width: '150px',
    uuid: 1,
  },
  {
    name: 'Type',
    width: '100px',
    uuid: 2,
  },
  {
    name: 'Default',
    width: '200px',
    flex_grow: 1,
    uuid: 3,
  },
  {
    name: 'Options',
    width: '200px',
    flex_grow: 1,
    uuid: 4,
  },
  {
    name: 'Description',
    width: '300px',
    uuid: 5,
  },
];

export const dropdown_rows = [
  {
    name: 'onChange',
    type: 'function',
    default: '(value) => {}',
    options: '',
    description: 'onChange function will return filter value',
    uuid: 1,
  },
  {
    name: 'onSelect',
    type: 'function',
    default: '(option) => {}',
    options: '',
    description: 'onSelect function will return the selected option',
    uuid: 2,
  },
  {
    name: 'left_icon',
    type: 'fontawesome',
    default: 'null',
    options: 'fontawesome icon',
    description: 'optional left icon for a dropdown',
    uuid: 3,
  },
  {
    name: 'right_icon',
    type: 'fontawesome',
    default: `['fas', 'chevron-down']`,
    options: 'fontawesome icon',
    description: 'optional right icon for a button',
    uuid: 4,
  },
  {
    name: 'default_value',
    type: 'string',
    default: '',
    options: '',
    description: 'default dropdown value',
    uuid: 5,
  },
  {
    name: 'margin',
    type: 'string',
    default: '0px',
    options: 'inline-css',
    description: 'adds margin to a dropdowns',
    uuid: 6,
  },
  {
    name: 'width',
    type: 'number',
    default: '0',
    options: 'inline-css',
    description: 'sets the dropdown max width',
    uuid: 7,
  },
  {
    name: 'options',
    type: 'array',
    default: '[]',
    options: '',
    description: 'takes an array of objects',
    uuid: 8,
  },
  {
    name: 'options_key',
    type: 'string',
    default: 'name',
    options: '',
    description: 'targets a different key inside the options array to display a value',
    uuid: 9,
  },
  {
    name: 'label',
    type: 'string',
    default: 'null',
    options: '',
    description: 'places a label above the dropdown',
    uuid: 10,
  },
  {
    name: 'transparent',
    type: 'boolean',
    default: 'false',
    options: 'true | false',
    description: 'removes the label, background, and borders and is used specifically for table cells',
    uuid: 11,
  },
  {
    name: 'theme',
    type: 'object',
    default: '{}',
    options: 'refer to theme',
    description: 'theme override for button',
    uuid: 12,
  },
  {
    name: 'background',
    type: 'string',
    default: 'null',
    options: 'hexcode',
    description: 'will override transparent and can color cells in a table',
    uuid: 13,
  },
  {
    name: 'height',
    type: 'number',
    default: '30',
    options: '',
    description: 'will change the height and line height of the dropdown',
    uuid: 14,
  },
  {
    name: 'disabled',
    type: 'boolean',
    default: 'false',
    options: 'true | false',
    description: 'disables the dropdown',
    uuid: 15,
  },
  {
    name: 'placeholder',
    type: 'string',
    default: 'select item...',
    options: '',
    description: 'placeholder when an item has not been selected',
    uuid: 16,
  },
  {
    name: 'text_align',
    type: 'string',
    default: 'left',
    options: '',
    description: 'aligns the text in the dropdown',
    uuid: 17,
  },
  {
    name: 'scroll_height',
    type: 'number',
    default: '200',
    options: '',
    description: 'sets the height of the options scroll window',
    uuid: 20,
  },
  {
    name: 'nullable',
    type: 'boolean',
    default: 'false',
    options: 'true | false',
    description: 'allows the dropdown to accept no option selected',
    uuid: 21,
  },
  {
    name: 'error_message',
    type: 'string',
    default: 'required',
    options: '',
    description: 'change the tooltip message when nullable is true',
    uuid: 18,
  },
];

export const options = [
  {
    name: 'Option 1',
    uuid: 1,
  },
  {
    name: 'Option 2',
    uuid: 2,
  },
  {
    name: 'Option 3',
    uuid: 3,
  },
  {
    name: 'Option 4',
    uuid: 4,
  },
  {
    name: 'Option 5',
    uuid: 5,
  },
  {
    name: 'Option 6',
    uuid: 6,
  },
  {
    name: 'Option 7',
    uuid: 7,
  },
  {
    name: 'Option 8',
    uuid: 8,
  },
];
