export const headers = [
  {
    name: 'Prop',
    width: '150px',
    uuid: 1,
  },
  {
    name: 'Type',
    width: '100px',
    uuid: 2,
  },
  {
    name: 'Default',
    width: '200px',
    flex_grow: 1,
    uuid: 3,
  },
  {
    name: 'Options',
    width: '200px',
    flex_grow: 1,
    uuid: 4,
  },
  {
    name: 'Description',
    width: '300px',
    uuid: 5,
  },
];

export const dropdown_rows = [
  {
    name: 'onChange',
    type: 'function',
    default: '() => {}',
    options: '',
    description: 'onChange function',
    uuid: 1,
  },
  {
    name: 'onSelect',
    type: 'function',
    default: '(option) => {}',
    options: '',
    description: 'onSelect function',
    uuid: 2,
  },
  {
    name: 'left_icon',
    type: 'fontawesome',
    default: 'null',
    options: '',
    description: 'optional fontawesome left icon',
    uuid: 3,
  },
  {
    name: 'right_icon',
    type: 'fontawesome',
    default: `['fas', 'chevron-down']`,
    options: '',
    description: 'optional fontawesome right icon',
    uuid: 4,
  },
  {
    name: 'default_value',
    type: 'string',
    default: 'null',
    options: '',
    description: 'default value for uncontrolled component',
    uuid: 5,
  },
  {
    name: 'value',
    type: 'string',
    default: 'null',
    options: '',
    description: 'value for controlled component',
    uuid: 6,
  },
  {
    name: 'margin',
    type: 'string | number',
    default: '0px',
    options: '',
    description: 'adds margin',
    uuid: 7,
  },
  {
    name: 'width',
    type: 'number',
    default: '0',
    options: '',
    description: 'sets max-width',
    uuid: 8,
  },
  {
    name: 'options',
    type: 'array',
    default: '[]',
    options: '',
    description: 'array of objects',
    uuid: 9,
  },
  {
    name: 'options_key',
    type: 'string',
    default: 'name',
    options: '',
    description: 'targets a different key inside the options array to display the value',
    uuid: 10,
  },
  {
    name: 'label',
    type: 'string',
    default: 'null',
    options: '',
    description: 'places a label above the dropdown',
    uuid: 11,
  },
  {
    name: 'transparent',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'removes the label, background, and borders',
    uuid: 12,
  },
  {
    name: 'theme',
    type: 'object',
    default: '{}',
    options: 'refer to theme',
    description: 'theme override',
    uuid: 13,
  },
  {
    name: 'background',
    type: 'hexcode | rgba',
    default: 'null',
    options: '',
    description: 'sets background color',
    uuid: 14,
  },
  {
    name: 'height',
    type: 'number',
    default: '30',
    options: '',
    description: 'sets the height and line-height',
    uuid: 15,
  },
  {
    name: 'disabled',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'disables the dropdown',
    uuid: 16,
  },
  {
    name: 'placeholder',
    type: 'string',
    default: 'select item...',
    options: '',
    description: 'placeholder for the dropdown',
    uuid: 17,
  },
  {
    name: 'text_align',
    type: 'string',
    default: 'left',
    options: '',
    description: 'sets text-align for the dropdown',
    uuid: 18,
  },
  {
    name: 'scroll_height',
    type: 'number',
    default: '200',
    options: '',
    description: 'sets the height of the options scroll window',
    uuid: 19,
  },
  {
    name: 'nullable',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'allows the dropdown to accept no options selected',
    uuid: 20,
  },
  {
    name: 'controlled',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'allows the dropdown to be controlled by the value prop',
    uuid: 21,
  },
  {
    name: 'error_message',
    type: 'string',
    default: 'required',
    options: '',
    description: 'tooltip message when nullable is true',
    uuid: 22,
  },
];

export const options = [
  {
    name: 'Option 1',
    uuid: 1,
  },
  {
    name: 'Option 2',
    uuid: 2,
  },
  {
    name: 'Option 3',
    uuid: 3,
  },
  {
    name: 'Option 4',
    uuid: 4,
  },
  {
    name: 'Option 5',
    uuid: 5,
  },
  {
    name: 'Option 6',
    uuid: 6,
  },
  {
    name: 'Option 7',
    uuid: 7,
  },
  {
    name: 'Option 8',
    uuid: 8,
  },
];
