export const headers = [
  {
    name: 'Prop',
    width: '150px',
    uuid: 1,
  },
  {
    name: 'Type',
    width: '100px',
    uuid: 2,
  },
  {
    name: 'Default',
    width: '200px',
    flex_grow: 1,
    uuid: 3,
  },
  {
    name: 'Options',
    width: '200px',
    flex_grow: 1,
    uuid: 4,
  },
  {
    name: 'Description',
    width: '300px',
    uuid: 5,
  },
];

export const table_headers = [
  {
    name: 'Company',
    width: '200px',
    sort_key: 'company',
    sort_direction: 'default',
    flex_grow: 1,
    uuid: 1,
  },
  {
    name: 'Currency',
    width: '100px',
    sort_key: 'currency',
    sort_direction: 'default',
    uuid: 2,
  },
  {
    name: 'Country',
    width: '200px',
    flex_grow: 1,
    uuid: 3,
  },
  {
    name: 'Location',
    width: '200px',
    uuid: 4,
  },
];

export const table_props = [
  {
    name: 'headers',
    type: 'array',
    default: '[]',
    options: 'see table headers',
    description: 'controls the column widths and sets the headers',
    uuid: 1,
  },
  {
    name: 'settings',
    type: 'object',
    default: '{}',
    options: 'see table settings',
    description: 'controls the table settings',
    uuid: 2,
  },
  {
    name: 'rows',
    type: 'array',
    default: '[]',
    options: '',
    description: 'sets the table data',
    uuid: 3,
  },
  {
    name: 'footer',
    type: 'object',
    default: '{}',
    options: 'see table footer',
    description: 'sets the footer component',
    uuid: 4,
  },
  {
    name: 'children',
    type: 'component',
    default: '',
    options: '',
    description: 'each child represents one cell in a row',
    uuid: 5,
  },
  {
    name: 'theme',
    type: 'object',
    default: '{}',
    options: 'refer to theme',
    description: 'theme override for table',
    uuid: 6,
  },
  {
    name: 'filter',
    type: 'string',
    default: 'null',
    options: '',
    description: 'pass a string to filter the table',
    uuid: 7,
  },
  {
    name: 'keywords',
    type: 'array',
    default: '[]',
    options: '',
    description: 'pass an array of string to filter the table',
    uuid: 8,
  },
];

export const settings_props = [
  {
    name: 'headers_show',
    type: 'boolean',
    default: 'true',
    options: '',
    description: 'controls the headers',
    uuid: 1,
  },
  {
    name: 'header_row_height',
    type: 'number',
    default: '28',
    options: '',
    description: 'controls each header height',
    uuid: 2,
  },
  {
    name: 'filter_key',
    type: 'string',
    default: 'null',
    options: '',
    description: 'filter key for the filter prop and is required for filter to work',
    uuid: 3,
  },
  {
    name: 'keyword_key',
    type: 'string',
    default: 'null',
    options: '',
    description: 'filter key for the keywords prop and is required for keywords to work',
    uuid: 4,
  },
  {
    name: 'rows_scroll',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'rows will scroll if the parent is { display: flex }',
    uuid: 5,
  },
  {
    name: 'rows_sticky',
    type: 'number',
    default: 'null',
    options: '',
    description: 'sticky rows attached to the bottom of the table',
    uuid: 6,
  },
  {
    name: 'rows_fill',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'pass a string to filter the table',
    uuid: 7,
  },
  {
    name: 'rows_flex',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'rows will ignore the set height and grow',
    uuid: 8,
  },
  {
    name: 'rows_striped',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'rows will be striped',
    uuid: 9,
  },
  {
    name: 'row_borders',
    type: 'boolean',
    default: 'true',
    options: '',
    description: 'adds cell borders to the table',
    uuid: 10,
  },
  {
    name: 'row_height',
    type: 'number',
    default: '30',
    options: '',
    description: 'controls each rows height',
    uuid: 11,
  },
  {
    name: 'row_highlight',
    type: 'boolean',
    default: 'true',
    options: '',
    description: 'controls the hover highlight for each row',
    uuid: 12,
  },
];

export const footer_props = [
  {
    name: 'submit_text',
    type: 'string',
    default: 'null',
    options: '',
    description: 'shows the footer button and displays the text',
    uuid: 1,
  },
  {
    name: 'submit_disabled',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'disables the footer button',
    uuid: 2,
  },
  {
    name: 'pagination',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'this hasnt been implemented yet',
    uuid: 3,
  },
  {
    name: 'onSubmit',
    type: 'function',
    default: '() => {}',
    options: '',
    description: 'fires the footer button',
    uuid: 4,
  },
];

export const data = [
  {
    company: 'Et Lacinia Vitae Industries',
    currency: '$19.26',
    country: 'Saint Vincent and The Grenadines',
    location: '8.06715, -10.10668',
    headers: table_headers,
    rows: [
      {
        company: 'Et Lacinia Vitae Industries',
        currency: '$19.26',
        country: 'Saint Vincent and The Grenadines',
        location: '8.06715, -10.10668',
        uuid: 1,
      },
      {
        company: 'Sed Molestie Sed Company',
        currency: '$64.16',
        country: 'Iceland',
        location: '61.09839, -57.82553',
        uuid: 2,
      },
      {
        company: 'Et Eros Company',
        currency: '$70.57',
        country: 'Egypt',
        location: '66.19368, 154.81886',
        uuid: 3,
      },
    ],
    uuid: 1,
  },
  {
    company: 'Sed Molestie Sed Company',
    currency: '$64.16',
    country: 'Iceland',
    location: '61.09839, -57.82553',
    headers: table_headers,
    rows: [
      {
        company: 'Et Lacinia Vitae Industries',
        currency: '$19.26',
        country: 'Saint Vincent and The Grenadines',
        location: '8.06715, -10.10668',
        uuid: 1,
      },
      {
        company: 'Sed Molestie Sed Company',
        currency: '$64.16',
        country: 'Iceland',
        location: '61.09839, -57.82553',
        uuid: 2,
      },
      {
        company: 'Et Eros Company',
        currency: '$70.57',
        country: 'Egypt',
        location: '66.19368, 154.81886',
        uuid: 3,
      },
    ],
    uuid: 2,
  },
  {
    company: 'Et Eros Company',
    currency: '$70.57',
    country: 'Egypt',
    location: '66.19368, 154.81886',
    headers: table_headers,
    rows: [
      {
        company: 'Et Lacinia Vitae Industries',
        currency: '$19.26',
        country: 'Saint Vincent and The Grenadines',
        location: '8.06715, -10.10668',
        uuid: 1,
      },
      {
        company: 'Sed Molestie Sed Company',
        currency: '$64.16',
        country: 'Iceland',
        location: '61.09839, -57.82553',
        uuid: 2,
      },
      {
        company: 'Et Eros Company',
        currency: '$70.57',
        country: 'Egypt',
        location: '66.19368, 154.81886',
        uuid: 3,
      },
    ],
    uuid: 3,
  },
  {
    company: 'Non Dui Industries',
    currency: '$31.12',
    country: 'Italy',
    location: '-41.50167, 115.08687',
    headers: table_headers,
    rows: [
      {
        company: 'Et Lacinia Vitae Industries',
        currency: '$19.26',
        country: 'Saint Vincent and The Grenadines',
        location: '8.06715, -10.10668',
        uuid: 1,
      },
      {
        company: 'Sed Molestie Sed Company',
        currency: '$64.16',
        country: 'Iceland',
        location: '61.09839, -57.82553',
        uuid: 2,
      },
      {
        company: 'Et Eros Company',
        currency: '$70.57',
        country: 'Egypt',
        location: '66.19368, 154.81886',
        uuid: 3,
      },
    ],
    uuid: 4,
  },
  {
    company: 'Dolor Fusce Incorporated',
    currency: '$86.28',
    country: 'Tajikistan',
    location: '-77.28159, 51.10934',
    headers: table_headers,
    rows: [
      {
        company: 'Et Lacinia Vitae Industries',
        currency: '$19.26',
        country: 'Saint Vincent and The Grenadines',
        location: '8.06715, -10.10668',
        uuid: 1,
      },
      {
        company: 'Sed Molestie Sed Company',
        currency: '$64.16',
        country: 'Iceland',
        location: '61.09839, -57.82553',
        uuid: 2,
      },
      {
        company: 'Et Eros Company',
        currency: '$70.57',
        country: 'Egypt',
        location: '66.19368, 154.81886',
        uuid: 3,
      },
    ],
    uuid: 5,
  },
  {
    company: 'Sem Vitae Aliquam Consulting',
    currency: '$52.75',
    country: 'Peru',
    location: '-53.2179, -16.96331',
    headers: table_headers,
    rows: [
      {
        company: 'Et Lacinia Vitae Industries',
        currency: '$19.26',
        country: 'Saint Vincent and The Grenadines',
        location: '8.06715, -10.10668',
        uuid: 1,
      },
      {
        company: 'Sed Molestie Sed Company',
        currency: '$64.16',
        country: 'Iceland',
        location: '61.09839, -57.82553',
        uuid: 2,
      },
      {
        company: 'Et Eros Company',
        currency: '$70.57',
        country: 'Egypt',
        location: '66.19368, 154.81886',
        uuid: 3,
      },
    ],
    uuid: 6,
  },
  {
    company: 'Non Lorem Vitae LLP',
    currency: '$51.62',
    country: 'El Salvador',
    location: '6.07701, 33.36416',
    headers: table_headers,
    rows: [
      {
        company: 'Et Lacinia Vitae Industries',
        currency: '$19.26',
        country: 'Saint Vincent and The Grenadines',
        location: '8.06715, -10.10668',
        uuid: 1,
      },
      {
        company: 'Sed Molestie Sed Company',
        currency: '$64.16',
        country: 'Iceland',
        location: '61.09839, -57.82553',
        uuid: 2,
      },
      {
        company: 'Et Eros Company',
        currency: '$70.57',
        country: 'Egypt',
        location: '66.19368, 154.81886',
        uuid: 3,
      },
    ],
    uuid: 7,
  },
  {
    company: 'Placerat Eget Limited',
    currency: '$62.46',
    country: 'Liberia',
    location: '-25.59097, 68.96981',
    headers: table_headers,
    rows: [
      {
        company: 'Et Lacinia Vitae Industries',
        currency: '$19.26',
        country: 'Saint Vincent and The Grenadines',
        location: '8.06715, -10.10668',
        uuid: 1,
      },
      {
        company: 'Sed Molestie Sed Company',
        currency: '$64.16',
        country: 'Iceland',
        location: '61.09839, -57.82553',
        uuid: 2,
      },
      {
        company: 'Et Eros Company',
        currency: '$70.57',
        country: 'Egypt',
        location: '66.19368, 154.81886',
        uuid: 3,
      },
    ],
    uuid: 8,
  },
  {
    company: 'Consequat Inc.',
    currency: '$80.09',
    country: 'Comoros',
    location: '44.28996, -1.31058',
    headers: table_headers,
    rows: [
      {
        company: 'Et Lacinia Vitae Industries',
        currency: '$19.26',
        country: 'Saint Vincent and The Grenadines',
        location: '8.06715, -10.10668',
        uuid: 1,
      },
      {
        company: 'Sed Molestie Sed Company',
        currency: '$64.16',
        country: 'Iceland',
        location: '61.09839, -57.82553',
        uuid: 2,
      },
      {
        company: 'Et Eros Company',
        currency: '$70.57',
        country: 'Egypt',
        location: '66.19368, 154.81886',
        uuid: 3,
      },
    ],
    uuid: 9,
  },
  {
    company: 'Magnis Dis Parturient Ltd',
    currency: '$57.12',
    country: 'Samoa',
    location: '-70.60207, 98.41223',
    headers: table_headers,
    rows: [
      {
        company: 'Et Lacinia Vitae Industries',
        currency: '$19.26',
        country: 'Saint Vincent and The Grenadines',
        location: '8.06715, -10.10668',
        uuid: 1,
      },
      {
        company: 'Sed Molestie Sed Company',
        currency: '$64.16',
        country: 'Iceland',
        location: '61.09839, -57.82553',
        uuid: 2,
      },
      {
        company: 'Et Eros Company',
        currency: '$70.57',
        country: 'Egypt',
        location: '66.19368, 154.81886',
        uuid: 3,
      },
    ],
    uuid: 10,
  },
];

export const settings_flex = {
  rows_scroll: true,
  rows_striped: true,
};

export const settings_sticky = {
  rows_sticky: 2,
  rows_scroll: true,
  row_borders: false,
};

export const settings_fill = {
  rows_fill: true,
  rows_scroll: true,
  header_row_height: 30,
  row_height: 32,
};

export const settings_highlights = {
  row_highlight: false,
  headers_show: false,
};
