export const headers = [
  {
    name: 'Prop',
    width: '150px',
    uuid: 1,
  },
  {
    name: 'Type',
    width: '100px',
    uuid: 2,
  },
  {
    name: 'Default',
    width: '200px',
    flex_grow: 1,
    uuid: 3,
  },
  {
    name: 'Options',
    width: '200px',
    flex_grow: 1,
    uuid: 4,
  },
  {
    name: 'Description',
    width: '300px',
    uuid: 5,
  },
];

export const calendar_props = [
  {
    name: 'onSelect',
    type: 'function',
    default: '() => {}',
    options: '',
    description: 'onSelect function returns a selected_date, start_date and finish_date',
    uuid: 1,
  },
  {
    name: 'calendar_panels',
    type: 'number',
    default: '1',
    options: '',
    description: 'panel default is not implemented and can only take 1',
    uuid: 2,
  },
  {
    name: 'calendar_days',
    type: 'numbers',
    default: '42',
    options: '42 | 49 | 56',
    description: 'will extend the number of days shown on the calendar panel',
    uuid: 3,
  },
  {
    name: 'calendar_display',
    type: 'boolean',
    default: 'true',
    options: '',
    description: 'shows the selected day or range dates on a separate panel',
    uuid: 4,
  },
  {
    name: 'calendar_presets',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'shows a preset panel with quick date selection',
    uuid: 5,
  },
  {
    name: 'preset_dates',
    type: 'array',
    default: '',
    options: '',
    description: 'takes an array of objects that fills the calendar presets panel',
    uuid: 6,
  },
  {
    name: 'calendar_range',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'transitions the calendar to a range picker',
    uuid: 7,
  },
  {
    name: 'selected_date',
    type: 'date | string',
    default: 'new Date()',
    options: '',
    description: 'the default date for the date picker',
    uuid: 8,
  },
  {
    name: 'start_date',
    type: 'date | string',
    default: 'new Date()',
    options: '',
    description: 'the default start date for the range date picker',
    uuid: 9,
  },
  {
    name: 'finish_date',
    type: 'date | string',
    default: 'new Date()',
    options: '',
    description: 'the default finish date for the range date picker',
    uuid: 10,
  },
  {
    name: 'min_date',
    type: 'date | string',
    default: 'null',
    options: '',
    description: 'the min date for the calendar',
    uuid: 11,
  },
  {
    name: 'max_date',
    type: 'date | string',
    default: 'null',
    options: '',
    description: 'the max date for the calendar',
    uuid: 12,
  },
  {
    name: 'valid_formats',
    type: 'array',
    default: `['M/D/YYYY', 'M-D-YYYY']`,
    options: '',
    description: 'takes an array of date formats',
    uuid: 13,
  },
  {
    name: 'output_format',
    type: 'string',
    default: 'M/D/YYYY',
    options: '',
    description: 'onSelect format for the selected dates',
    uuid: 14,
  },
];
