export const headers = [
  {
    name: 'Prop',
    width: '150px',
    uuid: 1,
  },
  {
    name: 'Type',
    width: '100px',
    uuid: 2,
  },
  {
    name: 'Default',
    width: '200px',
    flex_grow: 1,
    uuid: 3,
  },
  {
    name: 'Options',
    width: '200px',
    flex_grow: 1,
    uuid: 4,
  },
  {
    name: 'Description',
    width: '300px',
    uuid: 5,
  },
];

export const theme_rows = [
  {
    name: 'onDrop',
    type: 'function',
    default: '() => {}',
    options: '',
    description: 'onDrop function',
    uuid: 1,
  },
  {
    name: 'onClick',
    type: 'function',
    default: '() => {}',
    options: '',
    description: 'onClick function for the secondary button',
    uuid: 2,
  },
  {
    name: 'icon',
    type: 'fontawesome',
    default: "['far', 'file-alt']",
    options: '',
    description: 'fontawesome icon',
    uuid: 3,
  },
  {
    name: 'message',
    type: 'string',
    default: 'Drag & drop documents here',
    options: '',
    description: 'dropzone message',
    uuid: 4,
  },
  {
    name: 'button_variant',
    type: 'string',
    default: 'primary',
    options: 'primary | secondary | blue ...',
    description: 'color variants',
    uuid: 5,
  },
  {
    name: 'label',
    type: 'string',
    default: 'null',
    options: '',
    description: 'label for dropzone',
    uuid: 6,
  },
  {
    name: 'background',
    type: 'string',
    default: 'null',
    options: '',
    description: 'background color for dropzone',
    uuid: 7,
  },
  {
    name: 'transparent',
    type: 'bool',
    default: 'false',
    options: '',
    description: 'remove dropzone border and background',
    uuid: 8,
  },
  {
    name: 'width',
    type: 'string | number',
    default: '100%',
    options: '',
    description: 'dropzone width',
    uuid: 9,
  },
  {
    name: 'height',
    type: 'string | number',
    default: '200px',
    options: '',
    description: 'sets dropzone height, min-height is 150px',
    uuid: 10,
  },
  {
    name: 'accept',
    type: 'string',
    default: '',
    options: '',
    description: 'accepts a list of file types for the input',
    uuid: 11,
  },
  {
    name: 'theme',
    type: 'object',
    default: '{}',
    options: '',
    description: 'theme override',
    uuid: 12,
  },
  {
    name: 'margin',
    type: 'string | number',
    default: '0px',
    options: '',
    description: 'adds margin',
    uuid: 13,
  },
  {
    name: 'disabled',
    type: 'boolean',
    default: 'false',
    options: '',
    description: 'disables the button',
    uuid: 14,
  },
  {
    name: 'button_upload',
    type: 'string',
    default: 'Upload documents',
    options: '',
    description: 'upload documents button',
    uuid: 15,
  },
  {
    name: 'button_external',
    type: 'Import documents',
    default: 'null',
    options: '',
    description: 'controlled button for onClick prop',
    uuid: 16,
  },
];
