export const headers = [
  {
    name: 'Prop',
    width: '150px',
    uuid: 1,
  },
  {
    name: 'Type',
    width: '100px',
    uuid: 2,
  },
  {
    name: 'Default',
    width: '200px',
    flex_grow: 1,
    uuid: 3,
  },
  {
    name: 'Options',
    width: '200px',
    flex_grow: 1,
    uuid: 4,
  },
  {
    name: 'Description',
    width: '300px',
    uuid: 5,
  },
];

export const switch_rows = [
  {
    name: 'onClick',
    type: 'function',
    default: '() => {}',
    options: '',
    description: 'onClick function fires switch',
    uuid: 1,
  },
  {
    name: 'highlight',
    type: 'boolean',
    default: 'true',
    options: 'true | false',
    description: 'highlights switch label depending on checked',
    uuid: 2,
  },
  {
    name: 'prepend_label',
    type: 'string',
    default: 'null',
    options: '',
    description: 'switch prepend label',
    uuid: 3,
  },
  {
    name: 'append_label',
    type: 'string',
    default: 'null',
    options: '',
    description: 'switch appended label',
    uuid: 4,
  },
  {
    name: 'theme',
    type: 'object',
    default: '{}',
    options: 'refer to theme',
    description: 'theme override for switch',
    uuid: 5,
  },
  {
    name: 'checked',
    type: 'boolean',
    default: 'false',
    options: 'true | false',
    description: 'controls switch checked',
    uuid: 6,
  },
  {
    name: 'margin',
    type: 'string | number',
    default: '0px',
    options: '',
    description: 'sets switch margin',
    uuid: 7,
  },
  {
    name: 'width',
    type: 'number | string',
    default: '100%',
    options: '',
    description: 'sets switch width',
    uuid: 8,
  },
  {
    name: 'height',
    type: 'number',
    default: '30',
    options: '',
    description: 'sets switch height',
    uuid: 9,
  },
  {
    name: 'disabled',
    type: 'boolean',
    default: 'false',
    options: 'true | false',
    description: 'disables switch',
    uuid: 10,
  },
];
