export const routes = {
  ROOT: '/',
  INSTALLATION: '/install',
  THEME: '/theme',
  BUTTONS: '/buttons',
  DROPDOWNS: '/dropdowns',
  INPUTS: '/inputs',
  INPUTS_SPECIAL: '/inputs-special',
  MODALS: '/modals',
  MODALS_WIZARD: '/modals-wizard',
  TABLE_BASICS: '/table-basics',
  TABLE_HEADERS: '/table-headers',
  TABLES_ACCORDION: '/tables-accordion',
  DATA: '/data',
};
