export const routes = {
  ROOT: '/',
  INSTALLATION: '/install',
  THEME: '/theme',
  ACCORDION: '/accordion',
  CALENDAR: '/calendar',
  BUTTONS: '/buttons',
  SNACKBAR: '/snackbar',
  SWITCH: '/switch',
  DROPDOWNS: '/dropdowns',
  DROPZONE: '/dropzone',
  INPUTS: '/inputs',
  INPUTS_SPECIAL: '/inputs-special',
  MODALS: '/modals',
  MODALS_WIZARD: '/modals-wizard',
  TABLE_BASICS: '/table-basics',
  TABLE_FOOTER: '/table-footer',
  TABLE_VARIATIONS: '/table-variations',
  TABLE_HEADERS: '/table-headers',
  TABLE_ACCORDION: '/table-accordion',
  DATA: '/data',
};
